// ── Hero definitions, race bonuses, class labels ─────────────────────────────

import type { HeroClass, HeroRace, HeroDefinition, PrimaryAttributes } from "./characterTypes";
import { getRacePortrait, getClassIcon } from "@/lib/data/icons";

export const CDN = "https://molochdagod.github.io/ObjectStore";

export const RACE_BONUSES: Record<HeroRace, { label: string; bonus: string; icon: string; bonuses: Partial<PrimaryAttributes>; iconUrl: string }> = {
  human: { label: "Human", bonus: "+10% EXP gain", icon: "👤", bonuses: { tactics: 2, wisdom: 1 }, iconUrl: getRacePortrait("human") },
  elf: { label: "Elf", bonus: "+Mana regeneration", icon: "🧝", bonuses: { intellect: 2, agility: 1 }, iconUrl: getRacePortrait("elf") },
  dwarf: { label: "Dwarf", bonus: "+Mining efficiency", icon: "⛏️", bonuses: { endurance: 2, vitality: 1 }, iconUrl: getRacePortrait("dwarf") },
  orc: { label: "Orc", bonus: "+Melee damage", icon: "👹", bonuses: { strength: 2, vitality: 1 }, iconUrl: getRacePortrait("orc") },
  barbarian: { label: "Barbarian", bonus: "+HP regeneration", icon: "🪓", bonuses: { agility: 2, dexterity: 1 }, iconUrl: getRacePortrait("barbarian") },
  undead: { label: "Undead", bonus: "+Shadow resistance", icon: "💀", bonuses: { intellect: 1, endurance: 1, tactics: 1 }, iconUrl: getRacePortrait("undead") },
};

export const CLASS_LABELS: Record<HeroClass, { label: string; icon: string; iconUrl: string; description: string; color: string }> = {
  warrior: { label: "Warrior", icon: "⚔️", iconUrl: getClassIcon("warrior"), description: "Frontline tank and damage dealer. Masters of melee combat, blocking, and party defense.", color: "#cc3333" },
  mage: { label: "Mage Priest", icon: "🔮", iconUrl: getClassIcon("mage"), description: "Arcane spellcaster and divine healer. Masters of magic damage, barriers, and restoration.", color: "#6633cc" },
  worge: { label: "Worg", icon: "🐺", iconUrl: getClassIcon("worge"), description: "Primal shapeshifter. Beast transformation, regeneration, and savage ferocity.", color: "#33aa33" },
  ranger: { label: "Ranger", icon: "🏹", iconUrl: getClassIcon("ranger"), description: "Precision striker and shadow operative. Archery, stealth, traps, and critical hits.", color: "#cc9933" },
};

export const HERO_DEFINITIONS: HeroDefinition[] = [
  { characterId: "knight", name: "Knight", heroClass: "warrior", race: "human",
    baseAttributes: { strength: 14, vitality: 14, endurance: 8, intellect: 3, wisdom: 4, dexterity: 6, agility: 4, tactics: 5 },
    lore: "Stalwart defender. Heavy plate armor, trained in sword and shield." },
  { characterId: "golden_knight", name: "Golden Knight", heroClass: "warrior", race: "human",
    baseAttributes: { strength: 16, vitality: 16, endurance: 10, intellect: 2, wisdom: 3, dexterity: 4, agility: 3, tactics: 4 },
    lore: "Elite royal guard. Gold-plated armor, unyielding discipline." },
  { characterId: "soldier", name: "Soldier", heroClass: "warrior", race: "human",
    baseAttributes: { strength: 12, vitality: 12, endurance: 6, intellect: 3, wisdom: 4, dexterity: 8, agility: 6, tactics: 7 },
    lore: "Versatile frontliner. Chainmail and adaptability." },
  { characterId: "blue_soldier", name: "Blue Soldier", heroClass: "warrior", race: "human",
    baseAttributes: { strength: 13, vitality: 13, endurance: 7, intellect: 4, wisdom: 5, dexterity: 7, agility: 5, tactics: 4 },
    lore: "Royal guard corps. Blue tabard, sworn protector of the crown." },
  { characterId: "viking", name: "Viking", heroClass: "warrior", race: "barbarian",
    baseAttributes: { strength: 18, vitality: 14, endurance: 8, intellect: 2, wisdom: 2, dexterity: 6, agility: 4, tactics: 4 },
    lore: "Ferocious norse raider. Raw strength and berserker fury." },
  { characterId: "pirate", name: "Pirate", heroClass: "ranger", race: "human",
    baseAttributes: { strength: 8, vitality: 6, endurance: 4, intellect: 4, wisdom: 4, dexterity: 14, agility: 10, tactics: 8 },
    lore: "Sea-hardened swashbuckler. Quick blade, sharp eye, favored by fortune." },
  { characterId: "cowboy", name: "Cowboy", heroClass: "ranger", race: "human",
    baseAttributes: { strength: 6, vitality: 6, endurance: 4, intellect: 3, wisdom: 4, dexterity: 16, agility: 10, tactics: 9 },
    lore: "Dead-eye gunslinger. Fastest draw in any land." },
  { characterId: "ninja", name: "Ninja", heroClass: "ranger", race: "human",
    baseAttributes: { strength: 6, vitality: 5, endurance: 4, intellect: 5, wisdom: 3, dexterity: 14, agility: 16, tactics: 5 },
    lore: "Shadow assassin. Speed and precision over brute force." },
  { characterId: "ninja_sand", name: "Sand Ninja", heroClass: "ranger", race: "human",
    baseAttributes: { strength: 6, vitality: 5, endurance: 4, intellect: 8, wisdom: 5, dexterity: 12, agility: 12, tactics: 6 },
    lore: "Desert wind warrior. Combines stealth with sand magic." },
  { characterId: "wizard", name: "Wizard", heroClass: "mage", race: "elf",
    baseAttributes: { strength: 2, vitality: 4, endurance: 3, intellect: 18, wisdom: 14, dexterity: 5, agility: 4, tactics: 8 },
    lore: "Arcane master. Decades of study unlocked devastating spell power." },
  { characterId: "witch", name: "Witch", heroClass: "mage", race: "elf",
    baseAttributes: { strength: 2, vitality: 4, endurance: 3, intellect: 16, wisdom: 14, dexterity: 6, agility: 5, tactics: 8 },
    lore: "Dark sorceress. Curses, hexes, and forbidden magic." },
  { characterId: "elf", name: "Elf", heroClass: "ranger", race: "elf",
    baseAttributes: { strength: 5, vitality: 5, endurance: 4, intellect: 7, wisdom: 10, dexterity: 14, agility: 10, tactics: 3 },
    lore: "Woodland guardian. Unmatched archery and nature attunement." },
  { characterId: "worker", name: "Worker", heroClass: "warrior", race: "dwarf",
    baseAttributes: { strength: 14, vitality: 16, endurance: 10, intellect: 2, wisdom: 3, dexterity: 6, agility: 4, tactics: 3 },
    lore: "Hardened laborer turned fighter. Incredible stamina and toughness." },
  { characterId: "goblin", name: "Goblin", heroClass: "ranger", race: "orc",
    baseAttributes: { strength: 4, vitality: 5, endurance: 3, intellect: 5, wisdom: 2, dexterity: 14, agility: 14, tactics: 11 },
    lore: "Small, vicious, and impossibly lucky. Stabs first, asks never." },
  { characterId: "zombie_m", name: "Zombie", heroClass: "worge", race: "undead",
    baseAttributes: { strength: 14, vitality: 18, endurance: 12, intellect: 2, wisdom: 2, dexterity: 3, agility: 3, tactics: 4 },
    lore: "Undead brute. Relentless, feels no pain, regenerates from wounds.",
    beastFormModelId: "raptor" },
  { characterId: "zombie_f", name: "Zombie Queen", heroClass: "mage", race: "undead",
    baseAttributes: { strength: 3, vitality: 8, endurance: 6, intellect: 16, wisdom: 12, dexterity: 5, agility: 4, tactics: 4 },
    lore: "Cursed ruler. Commands dark magic and legions of undead." },
  { characterId: "adventurer", name: "Adventurer", heroClass: "warrior", race: "human",
    baseAttributes: { strength: 10, vitality: 10, endurance: 6, intellect: 5, wisdom: 5, dexterity: 8, agility: 7, tactics: 7 },
    lore: "Jack of all trades. Seasoned dungeon crawler, adaptable fighter." },
  { characterId: "animated_base", name: "Base Character", heroClass: "warrior", race: "human",
    baseAttributes: { strength: 8, vitality: 8, endurance: 6, intellect: 8, wisdom: 5, dexterity: 8, agility: 8, tactics: 7 },
    lore: "Universal template. Balanced in every way, master of none." },
  { characterId: "animated_human", name: "Human", heroClass: "warrior", race: "human",
    baseAttributes: { strength: 10, vitality: 10, endurance: 6, intellect: 6, wisdom: 5, dexterity: 8, agility: 7, tactics: 6 },
    lore: "Standard human fighter. Reliable, determined, and trainable." },
  { characterId: "animated_wizard", name: "Arcane Wizard", heroClass: "mage", race: "elf",
    baseAttributes: { strength: 2, vitality: 3, endurance: 2, intellect: 20, wisdom: 16, dexterity: 5, agility: 4, tactics: 6 },
    lore: "Supreme arcanist. Raw magic power rivals the gods." },
  { characterId: "animated_woman", name: "Warrior Woman", heroClass: "warrior", race: "human",
    baseAttributes: { strength: 10, vitality: 8, endurance: 5, intellect: 3, wisdom: 4, dexterity: 12, agility: 10, tactics: 6 },
    lore: "Fierce blade dancer. Speed and strength in equal measure." },
  { characterId: "animated_zombie", name: "Risen Dead", heroClass: "worge", race: "undead",
    baseAttributes: { strength: 12, vitality: 20, endurance: 10, intellect: 2, wisdom: 2, dexterity: 3, agility: 3, tactics: 6 },
    lore: "Reanimated horror. Shambling tank with supernatural resilience.",
    beastFormModelId: "raptor" },
  { characterId: "anne", name: "Anne", heroClass: "ranger", race: "human",
    baseAttributes: { strength: 6, vitality: 5, endurance: 3, intellect: 3, wisdom: 3, dexterity: 16, agility: 14, tactics: 8 },
    lore: "Lightning-fast ranger. Dual daggers, evasion specialist." },
  { characterId: "barbarian_glad", name: "Barbarian Gladiator", heroClass: "worge", race: "barbarian",
    baseAttributes: { strength: 20, vitality: 14, endurance: 8, intellect: 2, wisdom: 2, dexterity: 6, agility: 4, tactics: 2 },
    lore: "Arena champion. Primal rage and beast-like ferocity.",
    beastFormModelId: "raptor" },
  { characterId: "berserker", name: "Berserker", heroClass: "worge", race: "barbarian",
    baseAttributes: { strength: 18, vitality: 12, endurance: 6, intellect: 2, wisdom: 2, dexterity: 8, agility: 6, tactics: 4 },
    lore: "Rage-fueled berserker. Crosses the line between man and beast.",
    beastFormModelId: "raptor" },
  { characterId: "racalvin", name: "Racalvin", heroClass: "warrior", race: "human",
    baseAttributes: { strength: 12, vitality: 8, endurance: 6, intellect: 5, wisdom: 4, dexterity: 10, agility: 8, tactics: 5 },
    lore: "Master of six weapon styles. Versatile combat virtuoso." },
  { characterId: "human_base_mesh", name: "Human Base (Equipped)", heroClass: "warrior", race: "human",
    baseAttributes: { strength: 8, vitality: 8, endurance: 6, intellect: 8, wisdom: 5, dexterity: 8, agility: 8, tactics: 7 },
    lore: "Customizable template. Equipment defines the warrior." },
  { characterId: "hero", name: "Hero", heroClass: "warrior", race: "human",
    baseAttributes: { strength: 10, vitality: 10, endurance: 7, intellect: 7, wisdom: 6, dexterity: 8, agility: 8, tactics: 6 },
    lore: "Custom-forged champion. A blank slate shaped by choice and will." },
];

export function getHeroDefinition(characterId: string): HeroDefinition | undefined {
  return HERO_DEFINITIONS.find(h => h.characterId === characterId);
}
