// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/game-hud/Accessible.tsx": () => import("../components/mockups/game-hud/Accessible.tsx"),
  "./components/mockups/game-hud/Hierarchy.tsx": () => import("../components/mockups/game-hud/Hierarchy.tsx"),
  "./components/mockups/game-hud/HierarchyV1A.tsx": () => import("../components/mockups/game-hud/HierarchyV1A.tsx"),
  "./components/mockups/game-hud/HierarchyV1B.tsx": () => import("../components/mockups/game-hud/HierarchyV1B.tsx"),
  "./components/mockups/game-hud/HierarchyV1C.tsx": () => import("../components/mockups/game-hud/HierarchyV1C.tsx"),
  "./components/mockups/game-hud/Interaction.tsx": () => import("../components/mockups/game-hud/Interaction.tsx"),
  "./components/mockups/start-screen-usability/AccessibilityFirst.tsx": () => import("../components/mockups/start-screen-usability/AccessibilityFirst.tsx"),
  "./components/mockups/start-screen-usability/AffordanceFirst.tsx": () => import("../components/mockups/start-screen-usability/AffordanceFirst.tsx"),
  "./components/mockups/start-screen-usability/HierarchyFirst.tsx": () => import("../components/mockups/start-screen-usability/HierarchyFirst.tsx")
};
